### ISSUE TITLE
Implement gas measurement injection and wasm program analysis.

### ISSUE THREAD

**Issue by krl** [dusk-network/rusk-vm#115]
We need to figure out how to connect our gas usage to the token transfers.

Previous implementation had a separate balance for each contract that was subtracted from by the gas counter, but afaik this is not how our model actually works.

**Comment by autholykos** [comment]
This issue depends on getting feedback from @toghrulmaharramov about the correct gas estimation

**Comment by CPerezz** [comment]
I'm not sure #173 closes the issue @krl is mentioning in the issue comment (which is not really related to the title). 
Since the PR adds the gas instrumentation, but it doesn't link the gas consumption to anything. We should add linkage to a new issue.
