### ISSUE TITLE
Add BidCorrectness to verify_proof ABICall mapping to be able to verify it's proofs

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/rusk-vm#149]
If we want to impl the Bid contract we need to be able to verify the [BidCorrectnessProof](https://github.com/dusk-network/rusk/blob/b59e8ad7a6319beb8cb73160e6b696a652602ed7/contracts/bid/circuits/src/correctness.rs#L19).

This will block dusk-network/rusk/51

**Comment by autholykos** [comment]
The `area:ABI` label is reserved for the ABI sub-team atm ;)
