### ISSUE TITLE
`ReturnValue::cast` should not take ownership of `Store`

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/rusk-vm#159]
`Store` is taken ownership in `ReturnValue::cast` but its not used as owned value:

https://github.com/dusk-network/rusk-vm/blob/001ffcd8c1c003440d85c48797dfff0289a6319d/dusk-abi/src/lib.rs#L157-L165

This lead to anomalies in the contracts such as the need to own a `Store` to parse the result of external contract calls.

**Comment by krl** [comment]
deprecated by #178 which removes this parameter.
