### ISSUE TITLE
Automatically derive interfaces for wasm module/contract definitions.

### ISSUE THREAD

**Issue by krl** [dusk-network/rusk-vm#179]
(This issue was moved from [canonical](https://github.com/dusk-network/canonical/issues/12)

Goal:

Take this definition

#[derive(Clone, Canon, Default)]
pub struct Counter {
    value: i32,
}

#[derive(WasmModule)]
impl Counter {
    pub fn new(val: i32) -> Self { ... }
		
    pub fn read_value(&self) -> i32 { ... }

    pub fn increment(&mut self) { ... }
}
And create a module with two conditionally compiled versions. Have a look at the conditional compilation in the counter example.

A: The actual wasm, with two exports, "q" and "t", for query and transaction respectively.

B: A type with the same name, with static methods to create transactions and queries for this module.

(A + B): Shared static methods and data definitons, including static methods on the module type

**Comment by autholykos** [comment]
Closing as obsolete
