### ISSUE TITLE
Refactor the way `NetworkState` gets the configurations for its wasm modules

### ISSUE THREAD

**Issue by krl** [dusk-network/rusk-vm#221]
In order to configure gas cost etc from diagnostic tools, the module config should be settable by the consumers of the rusk-vm library.

**Comment by krl** [comment]
Additionally, move the Schedule to its own module, and make sure it's also configurable from consumers.

**Comment by moCello** [comment]
I decided hard-code the name of the configuration file into the `NetworkState` constructor and  (contrary to what is stated in the title of this issue) **not** to make `ModuleConfig` a parameter of the constructor. This is so we can still setup a `default` network-state without parameters and sensible configurations.

**Comment by miloszm** [comment]
I have a question about API change concerning config:
- should we extend NetworkState constructor with a constructor method accepting config? if so - config file path or config struct? 
- should we extend NetworkState::deploy to have per-contract config (here I assume it should be struct)
To sum up: 
- do we want per-state or per-contract config or both?
- with per-state, do we want config with filepath or config with struct?

**Comment by miloszm** [comment]
We could divide config to general settings and cost settings. Not sure if such division is necessary.
