### ISSUE TITLE
Add Wasmer Instrumentation 

### ISSUE THREAD

**Issue by ZER0** [dusk-network/rusk-vm#247]
This issue involves all steps needed for proper instrumentation of the WASM code and gas meter related issues, as required by the wasmi to wasmer migration. This involves deciding about the lifecycle and place of the gas meter and related structures, introducing wasmer api to be used for instrumentation (as a replacement for the phased out wasmi one), as well as weights given to particular WASM opcodes - which can be done via wasmer API. Gas and instrumentation related test changes also belong to the scope of this issue.

**Comment by miloszm** [comment]
Use wasmer_middleware_common for instrumentation
