### ISSUE TITLE
Specify the minimum viable gas retained when making an inter-contract call

### ISSUE THREAD

**Issue by autholykos** [dusk-network/rusk-vm#252]
**Describe what kind of specification you want to have created**
In case a contract does not specify the amount of gas allocated to the inter-contract call, then a constant needs to be specified in order to guarantee safe execution termination. This constant is an amount of gas that needs to be retained by the VM instance when executing an inter-contract call.

### Context

Previously, the intention was defined in the following description:

> When executing a transaction, Rusk VM instantiates a new VM instance for every inter-contract call, meaning that execution proceeds as a nested set of VM instances. Each VM instance is executed in a sandbox and therefore does not impact the state of the underlying VM instances if the aforementioned instance execution fails for some reason.
Each transaction is limited to a predefined number of nested instances that can exist concurrently, as well as limited in the percentage of total available gas that can be allocated to the next instance (both of those constants are yet to be defined). If a percentage of gas is not retained when initiating an inter-contract call, the execution may be unable to terminate if an Out-of-Gas (OOG) exception is thrown during the execution of the former call. When a certain portion of the gas is allocated to the instance, the said instance's context should assume that the total gas is equivalent to the gas allocated to the said instance. For example, if the transaction is allocated with 64,000 gas, 60,000 of which are passed on to the next instance, when calling gasLeft host function, the said instance should return with 60,000 minus any gas spent by the instance until that point. 
> An example of a use case in which the VM instance is required to be aware of the amount of gas allocated to the said instance is a dividend payment function, which loops through the input variables distributing dividends to the specified users. At the end of each iteration, the loop is required to check whether there is enough gas remaining to finalize another iteration or not. If the remaining gas is less then the amount required to complete another iteration, the function breaks the loop and returns to the underlying instance.

### Note 
- On the EVM normally this is a percentage of the gas allocation
- General recursion is not a problem since the execute method cannot be called within the call stack
- This is used to pay fees even when the execution fails
- Refers to #183

**Comment by ZER0** [comment]
Close in favor of #254
