### ISSUE TITLE
Support for transaction rollbacks

### ISSUE THREAD

**Issue by ureeves** [dusk-network/rusk-vm#263]
**Describe what you want implemented** 
Support for rolling the network state back to when certain transactions were not applied.

**Describe "Why" this is needed**
This is needed to address certain kinds of fault on the node side, where blocks may end up being rolled back.

**Describe alternatives you've considered**
Instead of keeping a single `Hamt` in the network state one could keep a `Vec<Hamt>` representing a stack of transitions - the contracts' state produced by applying a transaction on top the previous contracts' state.

```rust
/// previous
pub struct NetworkState {
    block_height: u64,
    contracts: Hamt<ContractId, Contract, ()>,
    modules: Rc<RefCell<HashMap<ContractId, BoxedHostModule>>>,
    module_cache: Arc<Mutex<HashMap<ContractId, Module>>>,
}

/// suggested
pub struct NetworkState {
    block_height: u64,
    snapshots: Vec<Map<ContractId, Contract>>,
    modules: Rc<RefCell<HashMap<ContractId, BoxedHostModule>>>,
    module_cache: Arc<Mutex<HashMap<ContractId, Module>>>,
}
```

Then, instead of discarding the previous state in favor of the new one, one appends the new state to the `Vec` and only discard when some transaction is deemed by the user to considered "final".

A `HashMap` of TX roots to `Hamt` was also considered, where instead of appending the new state to a `Vec` one would add it under a root and therefore allow for a tree of applied state transitions instead of only a stack, while also allowing the user to choose an arbitrary root for persistence and/or finality. It's an avenue worthy of consideration.

**Comment by ZER0** [comment]
Blocked by #265

**Comment by ureeves** [comment]
Expanding on the suggestion to use a map from root to the contracts' state. We could do something like:

```rust
type Root = 32 bytes?;

pub struct NetworkState {
    block_height: u64,
    snapshots: Map<Root, <Map<ContractId, Contract>>>,
    modules: Rc<RefCell<HashMap<ContractId, BoxedHostModule>>>,
    module_cache: Arc<Mutex<HashMap<ContractId, Module>>>,
}
```

This would enable transactions to be applied to an arbitrary root and reverting to an arbitrary root. What do you think @krl?
