### ISSUE TITLE
Replacing Canonical with rkyv

### ISSUE THREAD

**Issue by ZER0** [dusk-network/rusk-vm#264]
**Describe what you want implemented** 
Rusk-VM should use rkyv instead of Canonical. This leads to change contract calling conventions and generally speaking FFI.

**Describe "Why" this is needed**
We're moving our stack to rkyv to reduce gas cost and improve performance.

**Describe alternatives you've considered**
N/A

**Additional context**
In order to close this issue we should have just one simple contract that runs with the new stack. The rest of tests will be ignored and ported in follow up issues.

**Comment by autholykos** [comment]
Superseded by the cascade of issues marked for VM
