### ISSUE TITLE
CI is not run on default branch

### ISSUE THREAD

**Issue by ureeves** [dusk-network/rusk-vm#273]
**Describe the bug**
The CI doesn't run on the default branch. This means that coverage data is not generated for it and we can't track it with the badge. The same statement is valid for the GH badge.

**To Reproduce**
Look at the badges in the README.md.

**Expected behaviour**
I expect the badges to be representative of the current state of the default branch.

**Comment by autholykos** [comment]
Closing as less important than `minor` and we have no label for it
