### ISSUE TITLE
Missing feature `std`

### ISSUE THREAD

**Issue by ureeves** [dusk-network/rusk-vm#274]
**Describe the bug**
There's a `cfg_attr` implemented for `Schedule`, conditionally deriving `serde::Serialize` and `serde::Deserialize` when feature `std` is turned on. There is no such feature.

**To Reproduce**
N/A

**Expected behaviour**
Either have a feature enabling the derive - I suggest the name `serde` - or delete the `cfg_attr`.

**Comment by autholykos** [comment]
Closing as obsolete
