### ISSUE TITLE
Add documentations

### ISSUE THREAD

**Issue by ZER0** [dusk-network/rusk-vm#30]
We should document more the code, and try to generate it.
In the future we should also add the `Makefile` to publish it, as we already did in other repos.

Here some generate docs and repos as reference:

https://dusk-network.github.io/dusk-zerocaf/
https://dusk-network.github.io/dusk-poseidon-merkle/
https://dusk-network.github.io/Hades252/hades252/

**Comment by krl** [comment]
#65
