### ISSUE TITLE
Abistore should be able to allocate

### ISSUE THREAD

**Issue by krl** [dusk-network/rusk-vm#306]
**Describe what you want implemented** 
AbiStore should be able to allocate.

**Describe "Why" this is needed**
When the AbiStore requests data, it is initially written to the *scratch* buffer, however when the scratch buffer is full, the execution is halted with a panic.

**Describe alternatives you've considered**
Increasing the size of the scratch buffer to be much larger. However this is a waste of space when not used.

**Comment by miloszm** [comment]
at the moment, because of glue code generation, we have many scratch-buffers, one per wasm-exported function - I am not sure if this is optimal and how it will play out in the long run

**Comment by autholykos** [comment]
Closing as the work for this one is carried out in #321
