### ISSUE TITLE
Forward port from VM1 to VM2

### ISSUE THREAD

**Issue by ureeves** [dusk-network/rusk-vm#325]
**Describe what you want implemented** 
The PRs merged for VM1 after starting work on VM2 should be ported into VM2 to keep feature parity.

**Describe "Why" this is needed**
To keep feature parity between the VM2 implementation and the currently used VM1 we should apply the changes done to VM1 to VM2.

**Describe alternatives you've considered**
We considered rebasing to the current master or merging master into the `rusk_vm_2_0_rc`, however this would be prohibitively expensive in terms of time.

**Additional context**
A list of merged PRs following the start of work on VM2:

- [x] #284
- [x] #287
- [x] #288
- [x] #290
- [x] #298
- [x] #303 
- [x] #309 
- [x] #310 
- [x] #311 
- [x] #314
- [x] #315
- [x] #320
- [x] #337

Don't forget to update the CHANGELOG accordingly.

**Comment by miloszm** [comment]
Created issue #329 to port the improvement in VMError implementation from VM1 to VM2.

**Comment by ureeves** [comment]
Created issue https://github.com/dusk-network/rusk-vm/issues/362 to port the improvement in gas metering from VM1 to VM2.

**Comment by ureeves** [comment]
Since the existence of `origin` and `head` will be rethought, marking the task https://github.com/dusk-network/rusk-vm/pull/290 as done.

**Comment by ureeves** [comment]
Separate PRs created. Closing this issue.
