### ISSUE TITLE
Introduce Event System

### ISSUE THREAD

**Issue by ureeves** [dusk-network/rusk-vm#326]
**Describe what you want implemented** 
Contracts run by the virtual machine should be able to call a new host function, allowing them to emit a log of a certain event. A list of these logs should then be returned as a result of a transaction execution, in order of their emission.

The event logs should contain at least the following information:

```text
struct EventLog {
    contract_id,
    data,
}
```

where `contract_id` is the ID of the contract that emitted the event, and `data` is the data that the contract has passed in this event.

**Describe "Why" this is needed**
An event system may be used upstream for a myriad of use cases. They can serve as a logging mechanism, as pub-sub topics for taking action on specific data, etc...

**Describe alternatives you've considered**
N/A

**Additional context**
Upstream, event logs are stored as part of the blockchain. Their inclusion can be proven by using a structure similar to [Bloom filter](https://en.wikipedia.org/wiki/Bloom_filter).

**Comment by autholykos** [comment]
This is super-cool

**Comment by robinmario90** [comment]
Back to Focus because Eduardo is on holiday + dependency + issue with the check
