### ISSUE TITLE
Port VMError implementation improvements from VM1 to VM2

### ISSUE THREAD

**Issue by miloszm** [dusk-network/rusk-vm#329]
**Describe what you want implemented** 
VMError improvements have been made in VM1 based on the thiserror crate paradigm. We want to have the same improvements in VM2.

**Describe "Why" this is needed**
It is a significant improvement in code de-duplication, ease of use, reuse, and maintenance, done in VM1, this effort and benefit will be lost if we do not port its results to VM2.

**Describe alternatives you've considered**
We could keep the error code as is but that would mean that VM2 introduces a regression in relation to VM1.

**Additional context**
This effort is based on paradigm introduced by crate `thiserror`

**Comment by miloszm** [comment]
created a PR 336 which will fix this issue

**Comment by miloszm** [comment]
Changes for this issue are ready but wait on microkelvin PR #121 to be approved

**Comment by ureeves** [comment]
Closed by https://github.com/dusk-network/rusk-vm/pull/361
