### ISSUE TITLE
VM2 replace hash mocker with proper hash

### ISSUE THREAD

**Issue by miloszm** [dusk-network/rusk-vm#344]
**Describe what you want implemented** 
Choose proper hash function and replace currently used hash mocker

**Describe "Why" this is needed**
VM2 uses hash mocker which needs to be replaced by proper hash

**Describe alternatives you've considered**
N/A

**Additional context**
In VM1 store::hash from canonical was used and in VM2 until now hash mocker was used instead
The hashing is used for wasm module bytecode only
Note: further refactoring of bytecode related code will be done in issues #333 and #348. This issue is only about hash function replacement, in a narrower context than #333 and #348. Issue #333 will introduce structs for contract code and state, and hence, will provide opportunity to refactor the bytecode hashing code. On the other hand, #348 may deem hashing no longer needed at all.

**Comment by miloszm** [comment]
Change to blake2b causes significant slowdown - question remains: hash mocker is much faster yet it hashes only the last 32 bytes of module's bytecode, is there some faster alternative than blake2b for the purpose of hashing relatively short bytecode? What kind of hashing is optimal for this particular use case?

**Comment by ZER0** [comment]
The final version of the VM will hash not only the bytecode but also some metadata (see the final [contract format](https://github.com/dusk-network/cargo-bake/wiki/Dusk-Contract-File-Format)), so it will be possible to have two contract with the same code from different author etc.
