### ISSUE TITLE
Remove `fn init() {}` from contract proc macros

### ISSUE THREAD

**Issue by krl** [dusk-network/rusk-vm#356]
**Describe what you want implemented** 
Currently, every contract needs to have an empty `fn init()` for code-generation purposes. This is not ideal and seems like a bit of a messy workaround.

Instead put the glue code generation in the `state` definition.

**Describe "Why" this is needed**
General clarity and to avoid leaky workarounds.

**Describe alternatives you've considered**
No

**Additional context**

**Comment by miloszm** [comment]
relates to issue #331
