### ISSUE TITLE
Printing should be replaced by logging

### ISSUE THREAD

**Issue by julesdesmit** [dusk-network/rusk-vm#47]
we should consider using some kind of logging crate for data like this, and probably make it optional / user configurable.

_Originally posted by @krl in https://github.com/dusk-network/rusk-vm/pull/46_

**Comment by CPerezz** [comment]
This is taken into account in the new Epic created to implement logging support across all our our repos that will need it. This one is included there.

So closing this.

See: https://github.com/dusk-network/rusk/issues/45
