### ISSUE TITLE
Remove `phoenix` as dependencies from VM

### ISSUE THREAD

**Issue by ZER0** [dusk-network/rusk-vm#74]
Currently Phoenix is going under major changes, and the VM cannot compile without a working version of it.
Since a refactor of the code and host functions will be necessary anyway, we should remove the phoenix deps from the VM so we can continue on work on the VM until Phoenix v3 is ready.

See also: dusk-network/phoenix#50

**Comment by CPerezz** [comment]
Closed via #75
