### ISSUE TITLE
 Add the second contract storage that part to the smart contract storage actual definition

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/rusk-vm#76]
This second part of the contract storage consists on an indexed list of `PoseidonTree`s which the Smart Contract needs in order to perform Merkle Opening Proofs regarding the structures that the tree contains on its leaves.

Examples of these structures are: `Note` from phoenix and `StorageBid` from dusk-blindbid.

**Comment by ZER0** [comment]
The issue is now outdated.
