### ISSUE TITLE
Implement basic SmartContract storage capabilities in respect to `PoseidonTree`s 

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/rusk-vm#78]
As stated in #77 Contracts Need to be able to access `PoseidonTree`s in order to store(append), retrieve and mutate the data located on them leaves. They also need to iterate over the tree keys and they need to be able to access the specific tree they want to (in case there's more than one).

The interactions that appear on the specs and therefore, need to be supported as calls that the SC might do to the PoseidonTree storage indexed list is:

- Iterate over the list of Keys (since the values are just `StorageScalar`s.
- Annotate the keys in respect of a field (which can be a primitive Rust type or a `Scalar` as far as I can imagine now). It would be nice to do it as generic as possible to not constraint ourseleves too much. 
- Filter or retrieve some kind of iterator or vector of Keys in respect of `annotated_field is >= or <= than a certain value`.
- Append new Key-Values to the tree.
- Retrieve (getter) or modify (mutable getter) a Key-value pair of a `PoseidonTree`.
     - Append data or mutate it should return the index/position that the key-value is linked to in the tree.
- Generate a `PoseidonBranch` by providing the position of the leaf or the key related to the leaf.
-

**Comment by ZER0** [comment]
This issue is basically solved by other issues, we'll create a more atomic issue in case some feature listed above is still missing.
